// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv dotenv-expand
import dotenv from "dotenv";
import { expand } from "dotenv-expand";
import { defineConfig } from "prisma/config";

const env = dotenv.config();
expand(env);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
